version: '3.9'
networks:
  expense:
volumes:
  db_data:
services:
  # Backend Service
  backend:
    image: sunil0428/my_backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: sunil0428/my_mysql:v1
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql

  # Nginx Frontend
  frontend:
    image: sunil0428/my_frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend